name: Build and Publish V3 Docker Image
on:
  push:
    branches:
      - "v3"
      
jobs:
  build_v3:
    name: Build and Publish Ritsu V3
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/RitsuProject/ritsu-v3:latest
