name: Coverage

on: [push, pull_request]

jobs:
  code:
    name: Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Set up Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.7.7
        with:
          install-command: yarn --frozen-lockfile --check-files --silent

      - name: Coverage
        run: yarn test:coverage
#
#      - name: Upload coverage to Codecov
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#        run: bash <(curl -s https://codecov.io/bash)
