name: Type Check

on: [push, pull_request]

jobs:
  code:
    name: Type checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Set up Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.7.7
        with:
          install-command: yarn --frozen-lockfile --check-files --silent

      - name: Type check
        run: yarn tsc
